version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
  labels:
  - dependencies
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: main
  labels:
  - CI
