name: Building GitHub pages (CI)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMMIT_AUTHOR: OPTIMADE
      COMMIT_AUTHOR_EMAIL: dev@optimade.org

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.8

    - name: Install OPTIMADE
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install -r requirements.txt

    - name: Make pages
      run: ./make_pages.py

    - name: Build gh-pages branch locally
      run: ./commit.sh
