name: Building and deploying GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      COMMIT_AUTHOR: OPTIMADE
      COMMIT_AUTHOR_EMAIL: dev@optimade.org

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python requirements
      run: |
        python -m pip install -U pip
        pip install -U setuptools
        pip install -r requirements.txt

    - name: Make pages
      run: ./make_pages.py

    - name: Commit to gh-pages
      run: ./commit.sh

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
